[#term-technical-context]

// tag::EN[]
==== Technical Context

Shows the complete system as one <<term-blackbox,blackbox>> within its environment from a technical or deployment perspective. 
This includes, in particular, technical interfaces and communication channels as well as the relevant technical details of the neighboring systems.
The technical context thus supplements the (business context)(#term-business-context)) by mapping domain-specific interactions with neighboring systems to e.g. specific communication channels and technical protocols.

See <<term-context-view,Context View>>.


// end::EN[]

// tag::DE[]
==== Technischer Kontext

Zeigt das vollständige System als eine <<term-blackbox,Blackbox>> innerhalb seiner Umgebung aus einer technischen bzw. Verteilungsperspektive.
Dazu gehören insbesondere technische Schnittstellen und Kommunikationskanäle sowie die relevanten technischen Details der Nachbarsysteme.
Damit ergänzt der technische Kontext den (fachlicher Kontext)(#term-business-context)) um die Zuordnung der fachlichen Interaktionen mit Nachbarsystemen zu z. B. spezifischen Kommunikationskanälen und technischen Protokollen.

Siehe <<term-context-view,Kontextabgrenzung>>.


// end::DE[] 