[#term-trainer]

// tag::EN[]
==== Trainer
A trainer is a person who conducts a training course himself, provided that this is carried out within the framework of a accreditation granted to an accredited <<term-training-provider,training provider>>. Accordingly, accredited training providers may only organise and conduct CPSA® training courses with accredited trainers. Only accredited training providers can apply for trainer <<term-accreditation,accreditations>>.

// end::EN[]

// tag::DE[]
==== Schulungsleiter

Ein Trainer ist eine Person, die eine Schulung selbst leitet, mit der
Maßgabe, dass diese im Rahmen einer einem akkreditierten
<<term-training-provider,Schulungsanbieter>> gewährten Akkreditierung durchgeführt wird.
Entsprechend dürfen akkreditierte Schulungsanbieter nur
CPSA®-Schulungen mit akkreditierten Schulungsleitern organisieren und
durchführen. Nur akkreditierte Schulungsanbieter können
<<term-accreditation,Akkreditierungen>> von Schulungsleitern beantragen.


// end::DE[]
