[#term-tls]

// tag::EN[]
==== TLS

**T**ransport-**L**ayer-**S**ecurity is a set of protocols to cryptographically
secure the communication of two partys by the means of the
<<term-cia-triad,CIA-triad>>.
It is widely used for secure communication on the internet and the foundation for HTTPS.

TLS started as an update to its predecessor SSL (Secure Socket Layer) Version
3.0 and should be used now instead of SSL 
link:https://tools.ietf.org/html/rfc7568[see RFC7568 "Deprecating Secure Sockets Layer Version 3.0"].




// end::EN[]

// tag::DE[]
==== TLS

Transport-Layer-Security (Transportschichtsicherheit)
bezeichnet eine Reihe von Protokollen zum kryptographischen Schutz der
Kommunikation von zwei Parteien mit den Mitteln der
<<term-cia-triad,CIA-Triade>>. Es wird sehr häufig zur sicheren
Kommunikation im Internet genutzt und bildet die Grundlage für HTTPS.

TLS begann als Update seines Vorgängers SSL (Secure Socket Layer)
Version 3.0 und sollte nun statt SSL verwendet werden 
link:https://tools.ietf.org/html/rfc7568[siehe RFC7568 „Deprecating Secure Sockets Layer Version 3.0"].




// end::DE[] 