// tag::EN[]
==== Performance Efficiency Quality Attribute
Performance relative to the amount of resources used under stated conditions.

Resources can include other software products, the software and hardware configuration of the system, and materials (e.g. print paper, storage media).

Is composed of the following sub-characteristics: <<term-time-behaviour-quality-attribute,time behaviour>>, <<term-resource-utilization-quality-attribute,resource utilization>>, <<term-capacity-quality-attribute,capacity>>.

Refer to link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO 25010] website.

Category: Quality, ISO 25010

// end::EN[]

// tag::DE[]
==== Qualitätsmerkmal Leistungseffizienz

Leistung im Verhältnis zur Menge der unter angegebenen Bedingungen
genutzten Ressourcen.

Ressourcen können andere Softwareprodukte, die Software- und
Hardwarekonfiguration des Systems und Materialien (z.B. Druckerpapier,
Speichermedien) umfassen.

Es besteht aus folgenden Teilmerkmalen:
<<term-time-behaviour-quality-attribute,Zeitverhalten>>, <<term-resource-utilization-quality-attribute,Ressourcenverbrauch>>,
<<term-capacity-quality-attribute,Kapazität>>. 
Vgl. Website von link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO 25010].

Kategorie: Qualität, ISO 25010



// end::DE[]

