// tag::EN[]
==== Package Principles

Fundamental principles for designing the structure of software systems (<<ref-martin-2003,Martin-2003>>):

* <<term-reuse-release-equivalence-principle,Reuse/Release Equivalence Principle (REP)>>
* <<term-common-reuse-principle,Common Reuse Principle (CRP)>>
* <<term-common-closure-principle,Common Closure Principle (CCP)>>
* <<term-acyclic-dependencies-principle,Acyclic Dependencies Principle (ADP)>>
* <<term-stable-dependencies-principle,Stable Dependencies Principle (SDP)>>
* <<term-stable-abstractions-principle,Stable Abstractions Principle (SAP)>>

Robert C. Martin, who coined the "<<term-solid-principles,SOLID>>" acronym, also [introduced the Package Principles](link:http://butunclebob.com/ArticleS.UncleBob.PrinciplesOfOod[Robert C. Martin]) and frequently reiterated both in conjunction. Whereas the SOLID Principles target the level of classes, the Package Principles target the level of larger components that contain multiple classes and might get deployed independently.

Package- and SOLID Principles share the explicit goal of keeping software <<term-maintainability-quality-attribute,maintainable>> and avoiding the symptoms of degraded design: rigidity, fragility, immobility, and viscosity.

While Martin expressed the Package Principles in terms of large-scale components, they apply at other scales as well. Their core are universal principles like low coupling, high cohesion, single responsibility, hierarchical (acyclic) decomposition, and the insight that meaningful dependencies go from specific/unstable concepts to more abstract/stable ones (which echoes the <<term-dependency-inversion,DIP>>).

Category: Design-Principle


// end::EN[]

// tag::DE[]
==== Packaging-Prinzipien

Grundsätze für die Gestaltung der Struktur von Softwaresystemen
(<<ref-martin-2003,Martin-2003>>):

-   <<term-reuse-release-equivalence-principle,Reuse-Release-Equivalence-Prinzip (REP)>>

-   <<term-common-reuse-principle,Common-Reuse-Prinzip (CRP)>>

-   <<term-common-closure-principle,Common-Closure-Prinzip (CCP)>>

-   <<term-acyclic-dependencies-principle,Acyclic-Dependencies-Prinzip (ADP)>>

-   <<term-stable-dependencies-principle,Stable-Dependencies-Prinzip (SDP)>>

-   <<term-stable-abstractions-principle,Stable-Abstractions-Prinzip (SAP)>>

Robert C. Martin, der das Akronym „<<term-solid-principles,SOLID>>" geprägt
hat, hat auch die [Packaging-Prinzipien eingeführt](link:http://butunclebob.com/ArticleS.UncleBob.PrinciplesOfOod[Robert C. Martin])
und häufig beide zusammen angeführt. Während die SOLID-Prinzipien auf
die Klassen-Ebene abzielen, beziehen sich die Packaging-Prinzipien auf
die Ebene größerer Komponenten, die mehrere Klassen enthalten und
eventuell unabhängig verteilt werden.

Package- und SOLID-Prinzipien haben beide das ausdrückliche Ziel,
Software <<term-maintainability-quality-attribute,wartbar>> zu halten und die Anzeichen von
schlechtem Design, Rigidität, Fragilität, Immobilität und Viskosität
zu vermeiden.

Martin hat die Packaging-Prinzipien zwar bezogen auf große Komponenten
formuliert, sie gelten jedoch auch für alle anderen Größen. Ihr Kern
sind universelle Prinzipien, wie lose Kopplung, eindeutige
Verantwortung, hierarchische (azyklische) Zerlegung und die
Erkenntnis, dass sinnvolle Abhängigkeiten von spezifischen/instabilen
Konzepten zu abstrakteren/stabileren verlaufen (was sich im
<<term-dependency-inversion,DIP>> wiederfindet).

Kategorie: Entwurfsprinzip



// end::DE[]

