[#term-proxy]

// tag::EN[]
==== Proxy

(Design pattern) "A wrapper or agent object that is being called by the client to access the real serving object behind the scenes. Use of the proxy can simply be forwarding to the real object, or can provide additional logic. In the proxy extra functionality can be provided, for example caching when operations on the real object are resource intensive, or checking preconditions before operations on the real object are invoked. For the client, usage of a proxy object is similar to using the real object, because both implement the same interface."
(quoted from link:https://en.wikipedia.org/wiki/Proxy_pattern[Wikipedia])




// end::EN[]

// tag::DE[]
==== Stellvertreter / Proxy

(Entwurfsmuster) „Ein Wrapper oder Stellvertreterobjekt, das vom
Client aufgerufen wird, um auf das reale Serving-Objekt im Hintergrund
zuzugreifen. Die Funktion des Stellvertreters kann einfach in der
Weiterleitung an das reale Objekt oder die Bereitstellung zusätzlicher
Logik sein. Im Stellvertreter kann eine zusätzliche Funktionalität
bereitgestellt werden, beispielsweise Caching, wenn die Operationen
des realen Objekts ressourcenintensiv sind, oder Überprüfung von
Voraussetzungen vor dem Aufruf von Operationen des realen Objekts. Für
den Client ist die Verwendung eines Stellvertreterobjekts mit der
Verwendung des realen Objekts vergleichbar, da beide die gleiche
Schnittstelle implementieren." (Übersetztes englisches Zitat aus
link:https://de.wikipedia.org/wiki/Stellvertreter_(Entwurfsmuster)[Wikipedia])


// end::DE[] 