[#term-perfect-forward-secrecy]

// tag::EN[]
==== Perfect Forward Secrecy

Property of a cryptographic protocol were an attacker can't gain any
information about short-term session keys by compromising long-term keys.

Examples for protocols with perfect forward secrecy are TLS and OTR. If this
feature is enabled for <<term-tls,TLS>> and an attacker gains access to a servers private
key, previously recorded communication sessions can still not be decrypted.

Category: Security

// end::EN[]

// tag::DE[]
==== Perfect Forward Secrecy / Perfekte vorwärts gerichtete Geheimhaltung

Eigenschaft eines kryptografischen Protokolls, die darin besteht, dass
ein Angreifer durch Kompromittierung von Langzeitschlüsseln keine
Informationen über Kurzzeit-Sitzungsschlüssel erhalten kann.

Beispiele für Protokolle mit perfekter vorwärts gerichteter
Geheimhaltung sind TLS und OTR. Wenn diese Funktion für
<<term-tls,TLS>> aktiviert ist und ein Angreifer Zugriff auf den
privaten Schlüssel erhält, können früher aufgezeichnete
Kommunikationssitzungen dennoch nicht entschlüsselt werden.

Kategorie: Sicherheit




// end::DE[] 