[#term-principal]

// tag::EN[]
==== Principal

Principals in a security context are entities which have been authenticated and
can be assigned permissions to. A principal can be a user but for example also
other services or a process running on a system. The term is used in the 
link:https://docs.oracle.com/javase/8/docs/api/java/security/Principal.html[Java environment]
and throughout different authentication protocols (see 
link:https://www.rfc-editor.org/rfc/rfc2744[GSSAPI RFC2744] or
link:https://www.rfc-editor.org/rfc/rfc4121[Kerberos RFC4121]).





// end::EN[]

// tag::DE[]
==== Principal

Im Sicherheitskontext sind Principals Entitäten, die authentifiziert
wurden und denen Berechtigungen zugewiesen werden können. Principals
können Benutzer, aber auch andere Dienste oder ein auf einem System
laufender Prozess sein. Der Begriff wird in der
link:https://docs.oracle.com/javase/8/docs/api/java/security/Principal.html[Java-Umgebung]
und in verschiedenen Authentifizierungsprotokollen verwendet (siehe
link:https://www.rfc-editor.org/rfc/rfc2744[GSSAPI RFC2744] oder
link:https://www.rfc-editor.org/rfc/rfc4121[Kerberos RFC4121]).




// end::DE[] 