[#term-open-close-principle]

// tag::EN[]
==== Open-Close-Principle (OCP)

"Software entities (classes, modules, functions, etc.) should be open for extension, but closed for modification" (Bertrand Meyer, 1998).
In plain words:
To _add_ functionality (extension) to a system, you should _not need to modify_ existing code.
Part of Robin Martins "SOLID" principles for object-oriented systems.
Can be implemented in object oriented languages by interface inheritance, in a more general way as _plugins_.


// end::EN[]

// tag::DE[]
==== Open-Close-Prinzip (OCP)

Softwareentitäten (Klassen, Module, Funktionen usw.) sollten für
Erweiterungen offen, aber für Modifikationen geschlossen sein
(Bertrand Meyer, 1998). Einfach gesagt: Um eine Funktionalität zu
einem System *hinzuzufügen* (Erweiterung), sollte *keine Modifikation*
des vorhandenen Codes erforderlich sein. Teil der „SOLID-"Prinzipien
von Robin Martins für objektorientierte Systeme. Kann in
objektorientierten Sprachen durch
Schnittstellenvererbung, allgemeiner als
*Plugins*, implementiert werden.


// end::DE[] 