// tag::EN[]
==== Information Hiding

A fundamental principle in software design: Keep those design or implementation decisions
_hidden_ that are likely to change, thus protecting other parts of the system from  modification if these decisions or implementations are changed. Is one important
attributes of <<term-blackbox,blackboxes>>. Separates interface from implementation.

The term <<term-encapsulation,encapsulation>> is often used interchangeably with information hiding.

// end::EN[]

// tag::DE[]
==== Verbergen von Informationen

Ein grundlegendes Prinzip im Softwareentwurf: Entwurfs- oder
Implementierungsentscheidungen, die sich wahrscheinlich 채ndern, werden
*verborgen* gehalten, so dass andere Teile des Systems vor
Modifizierungen gesch체tzt sind, wenn diese Entscheidungen oder
Implementierungen ge채ndert werden. Eine der wichtigen Eigenschaften
von <<term-blackbox,Blackboxen>>. Trennt Schnittstelle von
Implementierung.

Der Begriff <<term-encapsulation,Kapselung>> wird
h채ufig austauschbar mit Verbergen von Informationen verwendet.



// end::DE[]

