[#term-design-pattern]

// tag::EN[]
==== Design Pattern

General or generic reusable solution to a commonly occurring problem within a given context in design.
Initially conceived by the famous architect link:https://en.wikipedia.org/wiki/Christopher_Alexander[Christopher Alexander],
the concept of _design patterns_ was taken up by software engineers.

In our opinion, every serious software developer should
know at least some patterns from the pioneering link:https://en.wikipedia.org/wiki/Design_Patterns[Gang-of-Four]
book by Erich Gamma (<<ref-gamma-1994>>) and his three allies.


// end::EN[]

// tag::DE[]
==== Entwurfsmuster

Allgemeine oder generische wiederverwendbare Lösung für ein gängiges
Problem in einem gegebenen Kontext beim Entwurf. Das ursprünglich von
dem berühmten Architekten link:https://en.wikipedia.org/wiki/Christopher_Alexander[Christopher Alexander]
erdachte Konzept von _Entwurfsmustern_ wurde von Softwareentwicklern
übernommen.

Unserer Ansicht nach sollte jeder ernsthafte Softwareentwickler
zumindest einige Muster aus dem bahnbrechenden Buch
link:https://en.wikipedia.org/wiki/Design_Patterns[Gang-of-Four]
von Erich Gamma (<<ref-gamma-1994>>) und seinen drei
Verbündeten kennen.


// end::DE[]
