[#term-deployment-view]

// tag::EN[]
==== Deployment View

Architectural view showing the technical infrastructure where a system or artifacts will be
deployed and executed.

"This view defines the physical environment in which the system is intended to run, including the hardware environment your system needs (e.g., processing nodes, network interconnections, and disk storage facilities), the technical environment requirements for each node (or node type) in the system, and the mapping of your software elements to the runtime environment that will execute them."
  (as defined by link:http://www.viewpoints-and-perspectives.info/home/viewpoints/deployment/[Rozanski+2011])

// end::EN[]

// tag::DE[]
==== Verteilungssicht

Architektursicht, die die technische Infrastruktur, in der ein System
oder Artefakte verteilt und ausgeführt werden, zeigt.

„Diese Sicht definiert die physische Umgebung, in der das System
laufen soll, einschließlich der Hardwareumgebung, die Ihr System
benötigt (z.B. Verarbeitungsknoten, Netzwerkverbindungen und
Speicherkapazitäten), der technischen Umgebungsanforderungen für jeden
Knoten (oder Knotentyp) im System und des Mappings Ihrer
Softwareelemente in Bezug auf die Laufzeitumgebung, die sie ausführt."
(Übersetztes englisches Zitat von
link:http://www.viewpoints-and-perspectives.info/home/viewpoints/deployment/[Rozanski+2011])



// end::DE[] 