// tag::EN[]
==== Design Principle

Set of guidelines that helps software developers to design and implement better solutions,
where "better" could, for example, mean one or more of the following:

  * low <<term-coupling,coupling>>.
  * high <<term-cohesion,cohesion>>.
  * <<term-separation-of-concern,separation of concerns>> or adherence to the <<term-single-responsibility-principle,Single Responsibility Principle>>.
  * adherence to the <<term-information-hiding,Information Hiding>> principle.
  * avoid *Rigidity*: A system or element is difficult to change because every change potentially
   affects many other elements.
  * avoid *Fragility*: When elements are changed, unexpected results, defects or otherwise negative consequences
   occur at other elements.
  * avoid *Immobility*: An element is difficult to reuse because it cannot be disentagled from the rest of the system.

// end::EN[]

// tag::DE[]
==== Entwurfsprinzip

Eine Reihe von Richtlinien, die Softwareentwicklern hilft, bessere
Lösungen zu entwerfen und zu implementieren, wobei „besser" bedeutet,
die folgenden *schlechten Eigenschaften* zu vermeiden:

-   Rigidität: Ein System oder Element ist schwer zu ändern, weil jede
    Änderung sich möglicherweise auf zahlreiche andere Elemente
    auswirkt.

-   Fragilität: Wenn Elemente geändert werden, treten unerwartete
    Ergebnisse, Fehler oder sonstige negative Folgen bei anderen
    Elementen auf.

-   Immobilität: Ein Element ist schwer wiederzuverwenden, weil es sich
    nicht aus dem übrigen System herauslösen lässt.

Diese Eigenschaften wurden von Robert Martin formuliert und stammen
von
link:https://www.oodesign.com/design-principles.html[OODesign.com]



// end::DE[]

