
// tag::EN[]

[#authors]
=== About the Authors

==== Gernot Starke

Dr. Gernot Starke (https://innoq.com[INNOQ] Fellow) is co-founder and avid user of the (open source) https://arc42.org[arc42] documentation template.
For more than 20 years he works as software architect, coach and consultant, conquering the challenges of creating effective software architectures for clients from various industries.

In 2008 Gernot co-founded the International Software Architecture Qualification Board (https://isaqb.org[iSAQB e.V.]) and since then supports it as an active member.

Gernot has authored several (German) books on software architecture and related topics and initiated this glossary.

He lives in Cologne with his wife (_Cheffe Uli_).

==== Ulrich Becker

Ulrich Becker works as principal consultant at http://www.methodpark.de[Method Park], focussing on software architecture and application lifecycle management.

Ulrich studied computer science at the University of Hamburg and the University of Erlangen-Nürnberg. He received his PhD from the University of Erlangen-Nürnberg in 2003 for his work on model-based distribution configuration. He then became group leader for the adaptive system software group at http://www.iis.fraunhofer.de/[Fraunhofer IIS].

Since 2005 Ulrich works as a trainer, consultant and coach at Method Park where he supports his clients in improving their development processes and methods. Most of his clients are from the automotive industry or other heavily regulated industries.

Ulrich is a founding member of http://isaqb.org[iSAQB e.V.] where he contributes to the foundation level and advanced level working groups. He lives in Erlangen with his family.

==== Matthias Bohlen

Matthias Bohlen, http://mbohlen.de[independent expert] for effective product development, started his career as a software developer in 1980. He wrote compilers for the MC68020 processor by Motorola which was quite a revolutionary device in those days where there was no IBM PC, yet. And the compilers really sold well.

Since then, Matthias has worked with countless software teams, helping them to get working software out the door without losing their mind. This is what he still does today.

Matthias is an active member of the http://www.isaqb.org[International Software Architecture Qualification Board], writes http://mbohlen.de[a blog], is being known in the Lean/Agile field, and speaks at conferences for software development.

==== Phillip Ghadir

Member of the board of INNOQ Deutschland GmbH. Since many years, Phillip consults
clients from various industries in topics around software-architecture,
technology and development. He co-founded the iSAQB and regularly conducts trainings
on software architecture.

==== Carola Lilienthal

Dr. Carola Lilienthal is software architect at and co-founder of the https://wps.de[WPS Workplace-Solutions].
For 20 years she has been working as a developer, project manager, coach, consultant and architect. Carola was an early adopter of Domain-Driven Design and agile movement and has successfully worked for numerous clients from various domains, mainly finance, insurance and logistics.

Since 2003, she has been analyzing software systems in Java, C++, C#, PHP, ABAP and gives advice to development teams how to improve the sustainability of their code. Carola speaks regularly on conferences and has written various articles as well as a book on sustainable software architecture.

Since 2008 Carola has been supporting the International Software Architecture Qualification Board (http://isaqb.org[iSAQB e.V.]) as an active member.

==== Mahbouba Gharbi

Mahbouba Gharbi is CIO of iTech Progress, book author and conference speaker.

Several years ago Mahbouba became president of the iSAQB. She lives in Mannheim with her family.


==== Simon Kölsch

Simon Kölsch works as a senior consultant at INNOQ with a focus on web architecture and security.

Simon is enthusiastic about solutions beyond the classical monolithic enterprise application, covering the architecture of distributed systems and their infrastructure, logging and monitoring.

He is not committed to one specific technology or programming language, but has a strong JVM background.

==== Alexander Lorz

Dr.-Ing. Alexander Lorz is a freelance software architecture trainer, IT consultant and developer. His first contact with IT systems dates back to the mid-1980s, and since then he has refused to give up his fascination for the science and craftsmanship of developing complex systems.

As an active member of the International Software Architecture Qualification Board (http://isaqb.org[iSAQB e.V.]) and the Foundation Level Working Group he contributes to the evolution of the foundation curriculum.

==== Michael Mahlberg

Michael Mahlberg runs his own https://consulting-guild.de[method consultancy] in Germany and spends most of his time supporting clients in their quest for more effective ways to work. Mostly by applying lean and agile concepts.

Running his own computer and software related companies since he was 18, he quickly came to realize that software architecture and (development) processes are in a way timeless aspects of the craft.

Nowadays a lot of his work focuses on processes and human interactions – a field in which he engages both professionally as well as pro bono (for example he is one of the people who started and run the http://lwscologne.de[Limited WIP Society Cologne]).

Michael's architectural work therefore tends to be dealing with the impact(s) and implications of architectural and process decisions _on each other_ and the relative optimization strategies.

==== Andreas Rausch

Prof. Dr. Andreas Rausch is head of the chair for Software Systems Engineering at Clausthal University of Technology.

He received his doctorate in 2001 at the Technical University of Munich, at the chair of Prof. Dr. Manfred Broy.
His main research interests in the field of software systems engineering are software architectures, model-based software development and process models.
He has published more than 70 international papers in these areas.

==== Roger Rhoades

Roger Rhoades is founder of https://albionacademy.de[Albion], a training and consulting company in Germany.

Roger has over 25 years of practical experience in the field of enterprise, business, and software architecture as well as management of international teams and projects. This practical experience is integrated into his training courses to ensure that class participants not only understand the theoretical content, but also the real-world challenges of its implementation.

Since 2012, Roger regularly presents at international conferences (e.g. EAMKon, Lean42 EAM, IT Strategy and Governance).

Since 2014, Roger has been an active member of the International Software Architecture Qualification Board (http://isaqb.org[iSAQB e.V.]). He actively supports the evolution of the foundation and advanced curricula, exam questions, and case studies in addition to the iSAQB glossary.

==== Sebastian Fichtner

Founder of https://www.flowtoolz.com[flowtoolz.com]. App engineer and consultant. Started coding in 1995. Passionate about architecture ever since. Does original apps, open source and projects for various clients. Loves Apple platforms and the language Swift.

// end::EN[]
