// tag::EN[]

==== Analysability Quality Attribute

Degree of effectiveness and efficiency with which it is possible to assess the impact on a product or system of an intended change to one or more of its parts, or to diagnose a product for deficiencies or causes of failures, or to identify parts to be modified.
Is a sub-characteristic of: <<term-maintainability-quality-attribute,maintainability>>.
Refer to https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO 25010] website.

Category: Quality, ISO 25010

// end::EN[]

// tag::DE[]

==== Qualitätsmerkmal Analysierbarkeit

Maß der Effektivität und Effizienz, mit dem die Auswirkung einer
geplanten Änderung an einem oder mehreren seiner Teile auf ein Produkt
oder System beurteilt, die Mängel oder Fehlerursachen eines Produkts
diagnostiziert oder zu modifizierende Teile identifiziert werden
können. Teilmerkmal von: <<term-maintainability-quality-attribute,Wartbarkeit>>. Vgl. Website
von https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO
25010]
.

Kategorie: Qualität, ISO 25010

// end::DE[]
