[#term-asymmetric-cryptography]

// tag::EN[]

==== Asymmetric Cryptography

Asymmetric cryptography algorithms are designed that the key which is used for
encryption is different from the key used for decryption. The key for
encryption is called "public-key" the key for decryption is called
"private-key". The public key can be published and used by anyone to encrypt
information only readable by the party owning the private-key for decryption.
See <<ref-schneier-1996,Schneier, Public-Key Algorithms, page 17>>.

Asymmetric cryptography is fundamental for <<term-pki,PKI>> and digital
signatures.

Category: Security

// end::EN[]

// tag::DE[]

==== Asymmetrische Kryptographie

Algorithmen der asymmetrischen Kryptographie sind so ausgelegt, dass
zur Verschlüsselung und zur Entschlüsselung unterschiedliche Schlüssel
verwendet werden. Der Schlüssel für die Verschlüsselung wird
„öffentlicher Schlüssel" genannt und der Schlüssel für die
Entschlüsselung „privater Schlüssel". Der öffentliche Schlüssel kann
veröffentlicht werden und von jedem zur Verschlüsselung von
Informationen verwendet werden; diese können nur von der Partei, die
im Besitz des privaten Schlüssels für die Entschlüsselung ist, gelesen
werden. Siehe <<ref-schneier-1996,Schneier, Public-Key Algorithms, Seite
17>>.

Asymmetrische Kryptographie ist die Grundlage für <<term-pki,PKI>>
und digitale Signaturen.

Kategorie: Sicherheit

// end::DE[]
