// tag::EN[]

==== Architecture Evaluation

Quantitative or qualitative assessment of a (software or system) architecture.
Determine if an architecture can achieve its target qualities or
quality attributes

See <<term-assessment,Assessment>>

D&gt; ###### Comment (Gernot Starke)
D&gt; In my opinion the terms _architecture analysis_ or _architecture assessment_ are more appropriate, as _evaluation_ contains _value_, implying numerical assessment or metrics, which is usually only _part_ of what you should do in architecture analysis.
D&gt;

// end::EN[]

// tag::DE[]

==== Architekturbewertung

Quantitative oder qualitative Beurteilung einer (Software- oder
System-) Architektur. Ermittlung, ob eine Architektur ihre
Zieleigenschaften oder Qualitätsmerkmale erreichen kann?

Siehe <<term-assessment,Beurteilung>>

D&gt; ###### Anmerkung (Gernot Starke)

D&gt;Ich halte die Begriffe _Architekturanalyse_ oder
D&gt;*Architekturbeurteilung* für passender, da in _Bewertung Wert_
D&gt;mitschwingt und eine numerische Beurteilung oder Kennzahlen impliziert
D&gt;werden, was üblicherweise nur ein _Teil_ dessen ist, was im Rahmen
D&gt;einer Architekturanalyse gemacht werden sollte.

// end::DE[]
