[#term-architecture-view]

// tag::EN[]

==== Architecture View

A representation of a system from a specific perspective. Important and well-known views are:

* <<term-context-view,Context view>>
* Building block view
* Runtime view
* Deployment view

<<bass>> and <<rozanski-11>> extensively discuss this concept.

Following ISO/IEC/IEEE 42010, an architecture view is a work product expressing the architecture of a system from the perspective of specific system concerns (as defined in ISO/IEC/IEEE 42010).


// end::EN[]

// tag::DE[]

==== Architektursicht

Eine Darstellung eines Systems aus einer spezifischen Perspektive.
Wichtige und bekannte Sichten:

* <<term-context-view,Kontextabgrenzung>>
* Bausteinsicht
* Laufzeitsicht
* Verteilungssicht

<<bass>> und <<rozanski-11>> erörtern dieses Konzept ausführlich.

Laut ISO/IEC/IEEE 42010 ist eine Architektursicht ein Arbeitsergebnis, das die Architektur eines Systems aus der Perspektive spezifischer Systembelange darstellt (gemäß Definition in ISO/IEC/IEEE 42010).

// end::DE[]
