// tag::EN[]

=== Accreditation Body

The application for <<term-accreditation,accreditation>> must be submitted through the _accreditation body_ designated by the iSAQB. The accreditation body is the contact point for all questions of the training provider during the <<term-accreditation,accreditation>>.
It coordinates the accreditation procedure, carries out the formal assessment of the documents submitted and organises the technical assessment in the <<term-audit-working-group,AUDIT WORKING GROUP>>.

// end::EN[]

// tag::DE[]

=== Akkreditierungsstelle

Der Antrag auf <<term-accreditation,Akkreditierung>> ist 체ber die vom iSAQB
benannte _Akkreditierungsstelle_ einzureichen. Die
Akkreditierungsstelle ist Ansprechpartner f체r alle Fragen des
Schulungsanbieters w채hrend der <<term-accreditation,Akkreditierung>>. Sie
koordiniert das Akkreditierungsverfahren, f체hrt die offizielle
Bewertung der eingereichten Unterlagen durch und organisiert die
technische Beurteilung in der <<term-audit-working-group,AUDIT-ARBEITSGRUPPE>>.
// end:DE[]
