[#term-quality-model]

// tag::EN[]
==== Quality Model
(from ISO 25010) A model that defines quality characteristics that relate to static properties of software and dynamic properties of the computer system and software products. The quality model provides consistent terminology for specifying, measuring and evaluating system and software product quality.

The scope of application of the quality models includes supporting specification and evaluation of software and software-intensive computer systems from different perspectives by those associated with their acquisition, requirements, development, use, evaluation, support, maintenance, quality assurance and control, and audit.

// end::EN[]

// tag::DE[]
==== Qualitätsmodell

(Aus ISO 25010) Ein Modell, das sich auf die statischen Eigenschaften
von Software und die dynamischen Eigenschaften von Computersystemen
und Softwareprodukten beziehende Qualitätseigenschaften definiert. Das
Qualitätsmodell liefert eine konsistente Terminologie zur
Spezifikation, Messung und Bewertung der System- und
Softwareproduktqualität.

Der Anwendungsumfang von Qualitätsmodellen umfasst die Unterstützung
der Spezifikation und Bewertung von Software und softwareintensiven
Computersystemen aus unterschiedlichen Perspektiven durch an ihrem
Erwerb, ihren Anforderungen, ihrer Entwicklung, ihrer Nutzung, ihrer
Bewertung, ihrem Support, ihrer Wartung, ihrer Qualitätssicherung und
-kontrolle sowie ihrem Audit beteiligte Personen.



// end::DE[] 