# Generates the glossary's derived AsciiDoc sources (port of the former Gradle tasks
# sortTermsAlphabetically and generateTranslationTables):
#
#   docs/1-terms/0-structure-{EN,DE}.adoc          alphabetical term index per language
#   docs/2-translations/gen-tt-{EN-DE,DE-EN}.adoc  translation tables from translations/*.json
#
# The curriculum-builder loads this file via build.config (ASCIIDOCTOR_COMMON_OPTS="-r ...");
# a preprocessor then regenerates the files before each render. Any error aborts the build.
#
# Run standalone to refresh the files, e.g. for IDE previews:
#   ruby extensions/glossary-generators.rb
require 'json'

module ISAQB
  module Glossary
    ROOT = File.expand_path '..', __dir__
    TERMS_DIR = File.join ROOT, 'docs', '1-terms'
    TRANSLATIONS_DIR = File.join ROOT, 'docs', '2-translations'
    TRANSLATIONS_JSON = File.join ROOT, 'translations', 'isaqb-terms-translated.json'
    GENERATOR = 'extensions/glossary-generators.rb'

    TERM_LANGUAGES = %w[EN DE].freeze
    TRANSLATION_LANGUAGES = { 'en' => 'English', 'de' => 'German' }.freeze

    class Error < StandardError; end

    module_function

    def generate
      generate_term_structures
      generate_translation_tables
    end

    def generate_once
      @generated ||= (generate; true)
    end


    # Each term file has an anchor ([#term-blackbox]) and, per language, a level-3 caption
    # (==== Black Box) inside its // tag::XX[] ... // end::XX[] block. The structure file
    # lists the term includes sorted by caption, with a "=== X" heading per initial letter.
    def generate_term_structures
      terms = collect_terms
      raise Error, "no term files found in #{TERMS_DIR}" if terms.empty?

      TERM_LANGUAGES.each do |lang|
        entries = terms.map { |term| [term[:captions][lang], term[:include]] }
        ('A'..'Z').each do |letter|
          heading = "==== #{letter}"
          next unless entries.any? { |caption, _| caption.downcase.start_with? heading.downcase }
          # "==== A" sorts directly before "==== Abstraction", so the heading lands above its terms.
          entries << [heading, "=== #{letter}"]
        end
        entries = entries.each_with_index.sort_by { |(caption, _), index| [caption.downcase, index] }

        write File.join(TERMS_DIR, "0-structure-#{lang}.adoc"), <<~ADOC
          // This file is autogenerated by #{GENERATOR} - please do not modify manually!

          // tag::#{lang}[]
          #{entries.map { |(_, include), _| include }.join "\n"}
          // end::#{lang}[]
        ADOC
      end
    end

    def collect_terms
      Dir.glob('**/term*.{ad,adoc,asciidoc}', base: TERMS_DIR).sort.map do |path|
        content = File.read File.join(TERMS_DIR, path), encoding: 'UTF-8'
        anchor = content[/\[#.*?\]/] || path
        captions = TERM_LANGUAGES.to_h do |lang|
          caption = content[/tag::#{lang}\[\].*?(^====.*?$).*?end::#{lang}\[\]/mi, 1]
          [lang, caption ? caption.strip.gsub(/\s{2,}/, ' ') : "==== #{anchor} (#{lang})"]
        end
        { captions: captions, include: "include::#{path}[{include_configuration}]" }
      end
    end


    def generate_translation_tables
      entries = parse_translations
      validate_translations entries

      en_de = {}
      de_en = Hash.new { |hash, key| hash[key] = [] }
      entries.each do |entry|
        translations = Array entry['de']
        en_de[entry['en']] = translations
        translations.each { |word| de_en[word] << entry['en'] }
      end
      de_en.each_value(&:sort!)

      write_translation_table 'gen-tt-EN-DE.adoc', 'en', 'de', en_de
      write_translation_table 'gen-tt-DE-EN.adoc', 'de', 'en', de_en
    end

    def parse_translations
      JSON.parse File.read(TRANSLATIONS_JSON, encoding: 'UTF-8')
    rescue JSON::ParserError => e
      raise Error, "#{TRANSLATIONS_JSON} is not valid JSON: #{e.message.lines.first(3).join.strip}"
    end

    def validate_translations entries
      raise Error, "#{TRANSLATIONS_JSON} must contain a JSON list" unless entries.is_a? Array

      errors = entries.each_with_index.filter_map do |entry, index|
        problem = translation_problem entry
        "entry #{index + 1} #{JSON.generate(entry)[0, 80]}: #{problem}" if problem
      end
      return if errors.empty?

      raise Error, "invalid entries in #{TRANSLATIONS_JSON}:\n  #{errors.join "\n  "}"
    end

    def translation_problem entry
      return 'is not a JSON object' unless entry.is_a? Hash
      return "has illegal keys #{entry.keys.inspect} (only 'en' and 'de' are supported)" unless entry.keys.sort == %w[de en]

      en, de = entry.values_at 'en', 'de'
      return "has no proper English ('en') source term" unless en.is_a?(String) && en.size > 1
      return "German ('de') translation is neither a string nor a list" unless de.is_a?(String) || de.is_a?(Array)
      return "German ('de') translation list may only contain non-empty strings" if de.is_a?(Array) && !de.all? { |word| word.is_a?(String) && !word.empty? }
      return "German ('de') translation list needs at least two entries (otherwise use a plain string)" if de.is_a?(Array) && de.size < 2
      return "German ('de') translation must not be empty" if de.is_a?(String) && de.empty?
      return 'English word must differ from German word' if en == de

      nil
    end

    def write_translation_table file_name, source, target, table
      rows = table.sort_by { |key, _| [key.downcase, key] }.map { |key, values| "|#{key} |#{values.join ', '} \n" }

      write File.join(TRANSLATIONS_DIR, file_name), <<~ADOC + rows.join + "\n|=== \n"

        // This file has been generated.
        //
        // DO NOT MODIFY, as changes will be overwritten.
        //
        // The following tables have been automatically generated from JSON by #{GENERATOR}.
        // They contain #{table.size} terms, generated on #{Time.now.strftime '%B %d, %Y'}.
        // -----------------------------

        [cols="1,1"]
        |===
        | *#{TRANSLATION_LANGUAGES[source]}* | *#{TRANSLATION_LANGUAGES[target]}*
      ADOC
    end

    def write path, content
      File.write path, content, encoding: 'UTF-8'
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  begin
    ISAQB::Glossary.generate
    puts 'glossary sources generated'
  rescue ISAQB::Glossary::Error => e
    abort "#{ISAQB::Glossary::GENERATOR}: #{e.message}"
  end
else
  require 'asciidoctor/extensions'

  Asciidoctor::Extensions.register do
    preprocessor do
      process do |_document, reader|
        ISAQB::Glossary.generate_once
        reader
      end
    end
  end
end
