// tag::EN[]
This book contains a glossary of _software architecture terminology_.

It can serve as a reference for preparation for the iSAQB® e.{nbsp}V.
 examination
_Certified Professional for Software Architecture - Foundation Level_©.

Please be aware: This glossary is *not* intended to be a primer or course book
on software architecture, but just a collection of definitions and links to further information.

Furthermore, you find proposals for <<section-translations,translations>> of the iSAQB® terminology, currently between English and German (and vice-versa).

Finally, this book contains numerous <<section-references,references>> to books and other resources, many of which we quoted in the definitions.

[CAUTION]
====
This book is work in progress.
====

Errors or omissions can also be reported in our issue tracker on link:https://github.com/isaqb-org/glossary/issues[GitHub], where the authors maintain the original sources for this book.

// end::EN[]

// tag::DE[]
Hier finden Sie ein Glossar für _Begriffe rund um Softwarearchitektur_.

Es ist als Quelle für die Vorbereitung auf die Prüfung zum _Certified Professional for Software Architecture - Foundation Level®_ des iSAQB® e.{nbsp}V. konzipiert.

Bitte beachten Sie: Dieses Glossar ist **nicht** als Einführung oder Lehrbuch zu Softwarearchitektur gedacht, sondern lediglich als eine Sammlung von Definitionen sowie von Links zu weiterführenden Informationen.

Außerdem finden Sie Vorschläge für <<section-translations,Übersetzungen>> der iSAQB® Fachausdrücke, aktuell für Deutsch nach Englisch und andersherum.

Zu guter Letzt beinhaltet dieses Buch zahlreiche <<section-references,Verweise>> auf Bücher sowie auf andere Quellen, aus welchen wir in etlichen Definitionen zitieren.

[CAUTION]
====
Dieses Buch ist in Arbeit und unfertig.
====

Sie können Fehler oder Auslassungen in unserem Issue-Tracker auf link:https://github.com/isaqb-org/glossary/issues[GitHub] melden, wo die Autoren die Quellen für dieses Buch verwalten.

// end::DE[]
