// tag::EN[]

=== Terms Can Be Referenced
All terms in the glossary have unique URLs to the (free) online version of the book therefore they can be universally referenced, both from online- and print documentation.

Our URL scheme is quite simple:

* The base URL is `https://public.isaqb.org/glossary/glossary-en.html`
* We just add the prefix `#term-` in front of the term to be referenced, then the term itself, with hyphens ("-") instead of blanks.

For example our description of the term _software architecture_ can be referenced (hyperlinked) with
 `https://public.isaqb.org/glossary/glossary-en.html#term-software-architecture`

Nearly all terms are hyperlinked with their full names, with very few examples that are referenced by their (common) abbreviations, like UML or DDD.

// end::EN[]


// tag::DE[]

=== Begriffe können referenziert werden
Alle Begriffe im Glossar haben eindeutige URLs auf die kostenlose Onlineversion des Buches. Daher können Sie durchgängig referenziert werden, in Onlinemedien wie auch in Printmedien.

Das Schema der URL ist sehr einfach:

* Die Basis-URL ist `https://public.isaqb.org/glossary/glossary-de.html`
* Wir fügen anschließend das Prefix `#term-` vor dem jeweiligen Begriff ein, der referenziert werden soll, dann den Begriff selbst, mit Bindestrichen anstelle von Leerzeichen. Allerdings ist es hierfür notwendig, den englischen Begriff zu kennen, da dieser als Anker verwendet wird.

Beispiel: Unsere Beschreibung des Begriffs "Softwarearchitektur" kann wie folgt mit einem Link referenziert werden:
`https://public.isaqb.org/glossary/glossary-de.html#term-software-architecture`

Fast alle Begriffe sind über ihren vollen Namen verlinkt, nur ein paar Ausnahmen werden über ihre (gängigen) Abkürzungen verlinkt, wie etwa UML oder DDD.

// end::DE[]

