[#term-software-architecture]

// tag::EN[]
==== Software Architecture

There exist several (!) valid and plausible definitions
of the term _Software Architecture_.

The following definition has been proposed by the link:https://en.wikipedia.org/wiki/IEEE_1471[IEEE 1471] standard:

A>Software Architecture: the fundamental organization of a system
A>embodied in its components, their relationships to each
A>other and to the environment and the principles guiding
A>its design and evolution.

The new standard ISO/IEC/IEEE 42010:2011 has adopted and revised the definition as follows:

A>Architecture: (system) fundamental concepts or properties of a system
A>in its environment embodied in its elements, relationships, and in
A>the principles of its design and evolution.

The key terms in this definition require some explanation:

* Components: Subsystems, modules, classes, functions or the more general term
 _building blocks_: structural elements of software: Components are usually implemented in a programming language, but can also be other artifacts that
(together) _make up the system_.
* Relationships: Interfaces, dependencies, associations - different names for the same feature: Components need to interact with other components to enable
 _separation of concerns_.
* Environment: Every system has some relationships
to its environment: data, control flow or events are transferred to
and from maybe different kinds of neighbours.
* Principles: Rules or conventions that hold for a system or several parts of it.
Decision or definition, usually valid for several elements of the system. Often
called _concepts_ or even _solution patterns_. Principles (concepts) are the foundation for _conceptual integrity_.


The _Software Engineering Institute_
maintains a link:http://www.sei.cmu.edu/architecture/start/glossary/classicdefs.cfm[collection of further definitions]

Although the term often refers to the _software architecture of an IT system_, it is also used to refer to _software architecture as an engineering science_.

Category: ISO-IEC-IEEE-42010


// end::EN[]

// tag::DE[]
==== Softwarearchitektur:

Es gibt mehrere (!) gültige und plausible Definitionen des Begriffs
*Softwarearchitektur*. Die link:https://en.wikipedia.org/wiki/IEEE_1471[IEEE 1471] Norm
schlägt folgende Definition vor:

In der neuen Norm ISO/IEC/IEEE 42010:2011 wurden die Definitionen
folgendermaßen übernommen und überarbeitet:

Die Schlüsselbegriffe dieser Definition bedürfen einer Erläuterung:

-   Komponenten: Teilsysteme, Module, Klassen, Funktionen oder
    allgemeiner gesagt *Bausteine*: Strukturelemente von Software:
    Komponenten werden üblicherweise in einer Programmiersprache
    implementiert, können aber auch andere Artefakte sein, die
    (zusammen) *das System bilden*.

-   Beziehungen: Schnittstellen, Abhängigkeiten, Assoziationen --
    verschiedene Bezeichnungen für dieselbe Funktion: Komponenten müssen
    mit anderen Komponenten interagieren, um *separation of concerns* zu
    ermöglichen.

-   Umgebung: Jedes System hat Beziehungen zu seiner Umgebung: Daten,
    Kontrollflüsse oder Ereignisse werden an möglicherweise
    unterschiedliche Arten von Nachbar und von diesen übertragen.

-   Prinzipien: Regeln oder Konventionen, die für ein System oder
    mehrere Teile eines Systems gelten. Entscheidung oder Definition,
    die in der Regel für mehrere Elemente des Systems gültig ist. Häufig
    *Konzepte* oder sogar *Lösungsmuster* genannt. Prinzipien (Konzepte)
    bilden die Grundlage für *konzeptionelle Integrität*.

Das *Software Engineering Institute* führt eine link:http://www.sei.cmu.edu/architecture/start/glossary/classicdefs.cfm[Sammlung weiterer Definitionen]

Auch wenn der Begriff sich oft auf die _Softwarearchitektur eines
IT-Systems_ bezieht, wird er auch benutzt, um sich auf
_Softwarearchitektur als Ingenieursdisziplin_ zu beziehen.

Kategorie: ISO-IEC-IEEE-42010


// end::DE[] 