// tag::EN[]
==== Stakeholder

Person or organization that can be affected by
or have in interest (_stake_) in a system, its development
or execution.

Examples include users, employees, owners, administrators, developers, designers, project- or product-managers, product-owner, project manager, requirements engineers, business-analysts, government agencies, enterprise architects etc.

Following ISO/IEC/IEEE 42010 a stakeholder is a (system) individual, team, organization, or classes thereof, having an interest in a system (as defined in ISO/IEC/IEEE 42010).

Such interest can be positive (e.g. stakeholder wants to benefit from the system), neutral (stakeholder has to test or verify the system) or negative (stakeholder is competing with the system or wants it to fail).

Category: ISO-IEC-IEEE-42010



// end::EN[]

// tag::DE[]
==== Stakeholder

Person oder Organisation, die von einem System, seiner Entwicklung
oder Ausführung betroffen sein kann oder ein Interesse (*stake*) daran
hat.

Beispiele sind Benutzer, Beschäftigte, Eigner, Administratoren,
Entwickler, Entwerfer, Manager, Product Owner, Projektmanager.

Gemäß ISO/IEC/IEEE 42010 sind Stakeholder (System) eine Einzelperson,
ein Team, eine Organisation oder Klassen davon, die ein Interesse an
einem System haben (gemäß Definition in ISO/IEC/IEEE 42010).

Kategorie: ISO-IEC-IEEE-42010



// end::DE[]

