[#term-software-architecture]

// tag::EN[]
==== Software Architecture

There exist several (!) valid and plausible definitions
of the term _Software Architecture_.

The following definition has been proposed by the link:https://en.wikipedia.org/wiki/IEEE_1471[IEEE 1471] standard:

====
Software Architecture: the fundamental organization of a system
embodied in its components, their relationships to each
other and to the environment and the principles guiding
its design and evolution.
====

The new standard ISO/IEC/IEEE 42010:2011 has adopted and revised the definition as follows:

====
Architecture: (system) fundamental concepts or properties of a system
in its environment embodied in its elements, relationships, and in
the principles of its design and evolution.
====


The key terms in this definition require some explanation:

* Components: Subsystems, modules, classes, functions or the more general term
 <<term-building-block,building blocks>>: structural elements of software. Components are usually implemented in a programming language, but can also be other artifacts that
(together) _make up the system_.
* Relationships: Interfaces, dependencies, associations – different names for the same feature: Components need to interact with other components to enable
 <<term-separation-of-concern,separation of concerns>>.
* Environment: Every system has some relationships
to its environment: data, control flow or events are transferred to
and from maybe different kinds of neighbours.
* Principles: Rules or conventions that hold for a system or several parts of it.
Decision or definition, usually valid for several elements of the system. Often
called <<term-concept,concepts>> or even _solution patterns_. Principles (concepts) are the foundation for <<term-conceptual-integrity,conceptual integrity>>.


The _Software Engineering Institute_
maintains a https://www.sei.cmu.edu/architecture/start/glossary/classicdefs.cfm[collection of further definitions]

Although the term often refers to the _software architecture of an IT system_, it is also used to refer to _software architecture as an engineering science_.


// end::EN[]

// tag::DE[]
==== Softwarearchitektur

Es gibt mehrere(!) gültige und plausible Definitionen des Begriffs
_Softwarearchitektur_. Die link:https://en.wikipedia.org/wiki/IEEE_1471[IEEE 1471] Norm
schlägt folgende Definition vor:

// FIXME translate!

====
Softwarearchitektur: die grundlegende Organisation eines Systems, wie sie sich in dessen Komponenten, deren Beziehungen zueinander und zur Umgebung sowie den Grundsätzen für Entwurf, Entwicklung und Evolution widerspiegelt.
====

In der neuen Norm ISO/IEC/IEEE 42010:2011 wurden die Definitionen
folgendermaßen übernommen und überarbeitet:

// FIXME translate!

====
Architecture: (system) fundamental concepts or properties of a system
in its environment embodied in its elements, relationships, and in
the principles of its design and evolution.
====

Die Schlüsselbegriffe dieser Definition bedürfen einer Erläuterung:

* Komponenten: Teilsysteme, Module, Klassen, Funktionen oder
allgemeiner gesagt <<term-building-block,Bausteine>>: Strukturelemente von Software.
Komponenten werden üblicherweise in einer Programmiersprache
implementiert, können aber auch andere Artefakte sein, die
(zusammen) _das System bilden_.
* Beziehungen: Schnittstellen, Abhängigkeiten, Assoziationen --
verschiedene Bezeichnungen für dieselbe Funktion: Komponenten müssen
mit anderen Komponenten interagieren, um <<term-separation-of-concern,Separation of Concerns>> zu
ermöglichen.
* Umgebung: Jedes System hat Beziehungen zu seiner Umgebung. Daten,
Kontrollflüsse oder Ereignisse werden an möglicherweise
unterschiedliche Arten von Nachbarn und von diesen übertragen.
* Prinzipien: Regeln oder Konventionen, die für ein System oder
mehrere Teile eines Systems gelten. Entscheidung oder Definition,
die in der Regel für mehrere Elemente des Systems gültig ist. Häufig
<<term-concept,Konzepte>> oder sogar _Lösungsmuster_ genannt. Prinzipien (Konzepte)
bilden die Grundlage für <<term-conceptual-integrity,konzeptionelle Integrität>>.

Das _Software Engineering Institute_ führt eine link:https://www.sei.cmu.edu/architecture/start/glossary/classicdefs.cfm[Sammlung weiterer Definitionen].

Der Begriff bezieht sich sowohl auf die _Softwarearchitektur eines IT-Systems_, wie auch benutzt, um sich auf _Softwarearchitektur als Ingenieursdisziplin_ zu beziehen (also als Aufgabe oder Rolle in Entwicklungsprojekten oder -organisationen).




// end::DE[]
