[#term-system]

// tag::EN[]
==== System

Collection of elements (building blocks, components etc)
organized for a common purpose.

In ISO/IEC/IEEE Standards a couple of system definitions are available:

* systems as described in [ISO/IEC 15288]: “systems that are man-made and may be configured with one or more of the following: hardware, software, data, humans, processes (e.g., processes for providing service to users), procedures (e.g. operator instructions), facilities, materials and naturally occurring entities”.
* software products and services as described in [ISO/IEC 12207].
* software-intensive systems as described in [IEEE Std 1471:2000]: “any system where software contributes essential influences to the design, construction, deployment, and evolution of the system as a whole” to encompass “individual applications, systems in the traditional sense, subsystems, systems of systems, product lines, product families, whole enterprises, and other aggregations of interest”.

// end::EN[]

// tag::DE[]
==== System

Sammlung von Elementen (Bausteinen, Komponenten usw.), die zu einem
gemeinsamen Zweck organisiert sind. In den ISO/IEC/IEEE-Normen gibt es
eine Reihe von Systemdefinitionen:

* Systeme gemäß Beschreibung in [ISO/IEC 15288]: Systeme, die vom
Menschen geschaffen wurden und mit einem oder mehreren der folgenden
Aspekte konfiguriert werden können: Hardware, Software, Daten,
Menschen, Prozesse (z.B. Prozesse zur Bereitstellung eines Dienstes
für Benutzer), Verfahren (z.B. Bedieneranweisungen), Anlagen,
Material und natürlich vorkommende Entitäten.
* Softwareprodukte und Dienste gemäß Beschreibung in [ISO/IEC 12207].
* Software-intensive Systeme gemäß Beschreibung in [IEEE Std 1471:2000]: jegliche Systeme, in denen Software wesentliche
Einflüsse zum Entwurf, zur Entwicklung, Verbreitung und
Weiterentwicklung des Systems als Ganzes beisteuert, um individuelle
Anwendungen, Systeme im herkömmlichen Sinne, Teilsysteme,
Systemverbünde, Produktlinien, Produktfamilien, ganze Unternehmen
und sonstige Interessensvereinigungen zu umspannen.


// end::DE[]
