[#term-sdl]

// tag::EN[]
==== SDL

A **Secure-Development-Lifecycle** is a companies usual software
development process with additional practices of engineering secure software.
This involves for example code reviews, architectural risk analyses, blackbox/whitebox and
penetration testing and many more additions.
The whole lifecycle of an application should be covered by the SDL, beginning
with the first requirements engineering tasks and ending with feedback from
operating the released software by fixing security issues.

See <<ref-mcgraw-2006>>, page 239.

// end::EN[]

// tag::DE[]
==== SDL

Ein **Secure-Development-Lifecycle** ist der übliche
Softwareentwicklungsprozess eines Unternehmens mit zusätzlichen
Praktiken zur Entwicklung von sicherer Software. Er umfasst
beispielsweise Code-Reviews, Architektur-Risikoanalysen,
Blackbox/Whitebox und Penetrationstests und zahlreiche weitere
Ergänzungen. Der SDL sollte den gesamten Lebenszyklus einer Anwendung,
von den ersten Anforderungsmanagementaufgaben bis zum Feedback aus dem
Betrieb der herausgegebenen Software durch Behebung von
Sicherheitsproblemen, abdecken.

Siehe <<ref-mcgraw-2006>>, Seite 239.

// end::DE[]
