[#term-security-goals]

// tag::EN[]
==== Security Goals

The goals are the key point of information security. They are a basic set of
information attributes which can be fulfilled or not depending on a systems
architecture and processes.

The most common agreed set of security goals is the so called "CIA triad":

* Confidentiality
* Integrity
* Availability

The "Reference Model of Information Assuarance and Security" (RIMAS) extends
this list by Accountability, Auditability, Authenticity/Trustworthiness,
Non-repudiation and Privacy.

These are typical examples for non-functional requirements related to security.

See <<ref-anderson-2008,"What is Security Engineering - Definitions", page 11>> or <<ref-rmias-2013,RMIAS>>.

Category: Security


// end::EN[]

// tag::DE[]
==== Schutzziele

Die Ziele sind der Hauptpunkt von Informationssicherheit. Sie sind ein
Basissatz an Informationseigenschaften, die abhängig von der
Architektur und den Prozessen eines Systems erfüllt werden können oder
nicht.

Die gängigste Gruppe von vereinbarten Schutzzielen ist die sogenannte
„CIA-Triade":

-   Vertraulichkeit (Confidentiality)

-   Integrität (Integrity)

-   Verfügbarkeit (Availability)

Das „Reference Model of Information Assurance and Security" (RIMAS)
erweitert diese Liste um Verantwortlichkeit, Prüfbarkeit,
Authentifizierbarkeit/Vertrauenswürdigkeit, Nichtabstreitbarkeit und
Datenschutz.

Dies sind die typischen Beispiele für nichtfunktionale Anforderungen
in Zusammenhang mit Sicherheit.

Siehe <<ref-anderson-2008,„What is Security Engineering - Definitions", Seite 11>> oder <<ref-rmias-2013,RMIAS>>.

Kategorie: Sicherheit


// end::DE[] 