[#term-make-illegal-states-unrepresentable]

// tag::EN[]
==== Make Illegal States Unrepresentable
This design principle ensures that states cannot occur that the system cannot process.
This is preferably done by designing the types, the data schema or the database schema appropriately.
If that is not possible, the system should validate states before construction rather than after.

See link:https://blog.janestreet.com/effective-ml-revisited/[Effective ML Revisited], link:https://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable/[Designing with types: Making illegal states unrepresentable], https://inside.java/2024/06/03/dop-v1-1-illegal-states/[Make Illegal States Unrepresentable - Data-Oriented Programming], link:https://funktionale-programmierung.de/en/2023/01/19/kotlin-validation.html[Functional Validation in Kotlin], and https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/[Parse, don’t validate].

// end::EN[]

// tag::DE[]
==== Make Illegal States Unrepresentable

Dieses Entwurfsprinzip stellt sicher, dass Zustände nicht auftreten können, die das System nicht verarbeiten kann.
Dies wird vorzugsweise erreicht, indem die Typen, das Datenschema oder das Datenbankschema entsprechend gestaltet werden.
Falls dies nicht möglich ist, sollte das System die Zustände vor der Konstruktion validieren, nicht hinterher.

See link:https://blog.janestreet.com/effective-ml-revisited/[Effective ML Revisited], link:https://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable/[Designing with types: Making illegal states unrepresentable], https://inside.java/2024/06/03/dop-v1-1-illegal-states/[Make Illegal States Unrepresentable - Data-Oriented Programming], link:https://funktionale-programmierung.de/2023/01/19/kotlin-validation.html[Funktionale Validierung in Kotlin], and https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/[Parse, don’t validate].
// end::DE[]

