[#term-model-view-viewmodel]

// tag::EN[]
==== Model-View-ViewModel (MVVM)

Architecture pattern, often used to implement user interfaces. It divides a
system into three interconnected parts (model, view, and view model) to separate
the following responsibilities:

* Model manages data and business logic of the system. Does not depend on the view
and the view model.
* View is the visible user interface of the application (or parts thereof).
* View Model serves as an intermediary between the View and the Model and holds the UI logic.
May depend on the model but not on the view.



// end::EN[]

// tag::DE[]
==== Model-View-ViewModel (MVVM)

Architekturmuster, das häufig zur Implementierung von Benutzeroberflächen verwendet wird.
Es unterteilt eine Anwendung in drei Teile (Model, View, und ViewModel):

* Das Modell verwaltet die Daten und die Geschäftslogik des Systems. Hängt nicht von View
und View-Model ab.
* View ist die sichtbare Benutzeroberfläche der Anwendung (oder Teilen davon).
* View-Model dient als Vermittler zwischen View und Model und enthält die UI-Logik.
Kann vom Model abhängen, aber nicht vom View.


// end::DE[]
