// tag::EN[]
==== Compatibility Quality Attribute
Degree to which a product, system or component can exchange information with other products, systems or components, and/or perform its required functions, while sharing the same hardware or software environment.
Is composed of the following sub-characteristics: <<term-co-existence-quality-attribute,co-existence>>, <<term-interoperability-quality-attribute,interoperabilty>>.
Refer to link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO 25010] website.

Category: Quality, ISO 25010

// end::EN[]

// tag::DE[]
==== Qualitätsmerkmal Kompatibilität

Maß, in dem ein Produkt, ein System oder eine Komponente Informationen
mit anderen Produkten, Systemen oder Komponenten austauschen und/oder
ihre geforderten Funktionen erfüllen können, während sie sich eine
Hardware- oder Softwareumgebung teilen. Es besteht aus folgenden
Teilmerkmalen: <<term-co-existence-quality-attribute,Koexistenz>>
<<term-interoperability-quality-attribute,Interoperabilität>>.
Vgl. Website von link:https://iso25000.com/index.php/en/iso-25000-standards/iso-25010[ISO 25010].

Kategorie: Qualität, ISO 25010



// end::DE[]

