[#term-context]

// tag::EN[]
==== Context (of a System)

"Defines the relationships, dependencies, and interactions between the system and its environment: People, systems, and external entities with which it interacts." (quoted from link:https://www.viewpoints-and-perspectives.info/home/viewpoints/context/[Rozanski-Woods])

Another definition from arc42:
"System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners (neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces." (quoted from link:https://docs.arc42.org[docs.arc42.org])

Distinguish between _business_ and _technical_ context:

* The **business** context (formerly called _logical_ context) shows the external relationships from a business- or non-technical perspective.
It abstracts from technical, hardware or implementation details.
Input-/Output relationships are named by their _business meaning_ instead of their technical properties.
* The **technical** context shows technical details, like transmission channel, technical protocol, IP-address, bus or similar hardware details.
Embedded systems, for example, often care for hardware-related information very early in development.


// end::EN[]

// tag::DE[]
==== Kontext (eines Systems)

"Definiert die Beziehungen, Abhängigkeiten und Interaktionen zwischen
dem System und seiner Umgebung: Menschen, Systeme und externe
Entitäten, mit denen es interagiert." (Übersetztes englisches Zitat
aus link:https://www.viewpoints-and-perspectives.info/home/viewpoints/context/[Rozanski-Woods])

Eine weitere Definition von arc42:
"System Scope und Kontext - wie der Name schon sagt - grenzen dein System (d.h. deinen Scope) von all seinen Kommunikationspartnern (benachbarte Systeme und Benutzer, d.h. den Kontext deines Systems) ab. Er legt damit die externen Schnittstellen fest." (zitiert aus link:https://docs.arc42.org[docs.arc42.org])

Unterscheide zwischen _geschäftlichem_ und _technischem_ Kontext:

* Der **geschäftliche** Kontext (früher _logischer_ Kontext genannt) zeigt die externen Beziehungen aus einer geschäftlichen oder nicht-technischen Perspektive.
Er abstrahiert von technischen, Hardware- oder Implementierungsdetails.
Input-/Output-Beziehungen werden nach ihrer _geschäftlichen Bedeutung_ benannt und nicht nach ihren technischen Eigenschaften.
* Der **technische** Kontext zeigt technische Details, wie Übertragungskanäle, technische Protokolle, IP-Adressen, Busse oder ähnliche Hardware-Details.
Eingebettete Systeme zum Beispiel interessieren sich oft schon sehr früh in der Entwicklung für hardwarebezogene Informationen.


// end::DE[]
