[#term-consistency]

// tag::EN[]
==== Consistency

A consistent systems does not contain contradictions.

* Identical problems are solved with identical (or at least similar) approaches.
* Degree, to which data and their relations comply to validation rules.
* Clients (of a database) get identical results for identical queries (e.g. Monotonic-Read-Consistency, Monotonic-Write-Consistency, Read-Your-Writes-Consistency etc.)
* With respect to behavior: Degree, to which a system behaves coherent, replicable and reasonable.


// end::EN[]

// tag::DE[]
==== Konsistenz

Ein konsistentes System enthält keine Widersprüche.

* Identische Probleme werden mit identischen (oder zumindest gleichartigen) Ansätzen gelöst.
* Maß, in dem Daten und ihre Beziehungen Validierungsregeln entsprechen.
* Clients (einer Datenbank) erhalten bei identischen Abfragen identische Ergebnisse (z.B. Monotonic-Read-Consistency, Monotonic-Write-Consistency, Read-Your-Writes-Consistency etc.)
* In Bezug auf Verhalten: Maß, in dem ein System sich kohärent, reproduzierbar und vernünftig verhält.

// end::DE[]
