[#term-ca]

// tag::EN[]
==== CA

A **C**ertificate **A**uthority issues digital certificates to a given subject
in a <<term-pki,PKI>>. Usually there is a trust established to this authority
which results in the same trust level to the issued certificates.

An example is the widely used TLS-PKI where every browser includes the
root-certificates of a defined list of CAs. These CAs then check the identity
of a given internet domain owner and digitally sign his certificate for the use
with <<term-tls,TLS>>.



// end::EN[]

// tag::DE[]
==== CA

Ein Zertifizierungsstelle (Certificate Authority, CA) stellt digitale
Zertifikate für ein gegebenes Subjekt in einer <<term-pki,PKI>>
aus. Üblicherweise besteht Vertrauen in diese Stelle, das zum gleichen
Maß an Vertrauen in die ausgestellten Zertifikate führt.

Ein Beispiel ist die weitverbreitete TLS-PKI, bei der jeder Browser
die Wurzelzertifikate einer festgelegten Liste von CA enthält. Diese
CA überprüfen dann die Identität eines gegebenen
Internet-Domaininhabers und signieren sein Zertifikat digital für die
Verwendung mit <<term-tls,TLS>>.




// end::DE[]
