// tag::EN[]
==== Concern

"A _concern_ about an architecture is a requirement, an objective, a constraint, an intention, or an aspiration a stakeholder has for that architecture." (quoted from <<Rozanski+11>>, chapter 8)

Following ISO/IEC/IEEE 42010 a concern is defined as (system) interest in a system relevant to one or more of its stakeholders (as defined in ISO/IEC/IEEE 42010).

Note, a concern pertains to any influence on a system in its environment, including developmental, technological, business, operational, organizational, political, economic, legal, regulatory, ecological and social influences.

Category: ISO-IEC-IEEE-42010


// end::EN[]

// tag::DE[]
==== Belang

*Belange* in Bezug auf eine Architektur sind Anforderungen, Ziele,
Einschränkungen, Absichten oder Bestrebungen eines Stakeholders für
diese Architektur. (<<Rozanski+11>>, Kapitel 8)

Gemäß ISO/IEC/IEEE 42010 ist Belang definiert als (System) Interesse
an einem System, das für einen oder mehrere Stakeholder relevant ist
(gemäß Definition in ISO/IEC/IEEE 42010).

Belange beziehen sich auf jegliche Einflüsse auf ein System in seiner
Umgebung, wie Entwicklungs-, Geschäfts- und Betriebseinflüsse sowie
technologische, organisatorische, politische, wirtschaftliche,
rechtlichen, regulatorische, ökologische und soziale Einflüsse.

Kategorie: ISO-IEC-IEEE-42010



// end::DE[]

