// tag::EN[]
==== Context (of a System)

"Defines the relationships, dependencies, and interactions between the system and its environment: People, systems, and external entities with which it interacts." (quoted from [Rozanski-Woods](https://www.viewpoints-and-perspectives.info/home/viewpoints/context/))

Another definition from arc42:
"System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners (neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces." (quoted from [docs.arc42.org](https://docs.arc42.org))

Distinguish between _business_ and _technical_ context:

* The **business** context (formerly called _logical_ context) shows the external relationships from a business- or non-technical perspective. 
It abstracts from technical, hardware or implementation details.
Input-/Output relationships are named by their _business meaning_ instead of their technical properties.

* The **technical** context shows technical details, like transmission channel, technical protocoll, IP-address, bus or similar hardware details. 
Embedded systems, for example, often care for hardware-related information very early in development. 


// end::EN[]

// tag::DE[]
==== Kontext (eines Systems)

„Definiert die Beziehungen, Abhängigkeiten und Interaktionen zwischen
dem System und seiner Umgebung: Menschen, Systeme und externe
Entitäten, mit denen es interagiert." (Übersetztes englisches Zitat
aus
[Rozanski-Woods](http://www.viewpoints-and-perspectives.info/home/viewpoints/context/))

FIXME: Hier fehlt noch was



// end::DE[]

