[#term-hyrums-law]

// tag::EN[]
==== Hyrums Law

Hyrums Law (named after Google engineer Hyrum Wright) states that with a large enough number of consumers, every observable behavior of your interface will be dependended upon by somebody.
The implication of Hyrums Law is that every version that changes observable behavior has the potential to break consumers, even if it's a change that is covered by a forward-compatible design of the interface.
https://www.youtube.com/watch?v=5Wdgjw6IGDM[Here's a video with Hyrum Wright speaking about "Hyrum's Law: Hyrum Wright on Programming over Time".]

// end::EN[]

// tag::DE[]
==== Hyrums Law

Hyrums Law (benannt nach dem Google-Ingenieur Hyrum Wright) besagt, dass bei einer ausreichend großen Anzahl von Nutzern irgendjemand von jedem beobachtbare Verhalten einer Schnittstelle abhängen wird.
Die Implikation von Hyrums Gesetz ist, dass jede Version, die beobachtbares Verhalten ändert, das Potenzial hat, Verbraucher zu brechen, selbst wenn es eine Änderung ist, die durch ein vorwärtskompatibles Design der Schnittstelle abgedeckt ist.
https://www.youtube.com/watch?v=5Wdgjw6IGDM[Hier ist ein (englisches) Video in dem Hyrum Wright über Hyrums Law spricht: "Hyrum's Law: Hyrum Wright on Programming over Time".]

// end::DE[]
