[#term-waterfall-development]

// tag::EN[]

[#term-waterfall-development]
==== Waterfall Development

Development approach "where you gather all the requirements up front, do all necessary design, down to a detailed level, then hand the specs to the coders, who write the code; then you do testing (possibly with a side trip to IntegrationHell) and deliver the whole thing in one big end-all release. Everything is big including the risk of failure." (quoted from the http://c2.com/cgi/wiki?IterativeDevelopment[C2 wiki])

See also <<term-iterative-development,_iterative development_>>.

// end::EN[]

// tag::DE[]
[[term-waterfall-development]]
==== Wasserfall-Entwicklung

Entwicklungsansatz, „bei dem man alle Anforderungen vorab
zusammenträgt, den gesamten erforderlichen Entwurf bis runter auf
Detailebene macht und dann die Spezifikationen an die Coder, die den
Code schreiben, weitergibt; dann werden Tests durchgeführt (eventuell
mit einem Abstecher in die Integrationshölle) und schließlich wird das
Ganze mit einem großen abschließenden Release geliefert. Alles ist
groß, auch die Gefahr des Scheiterns.&quot; (Übersetztes englisches Zitat
aus
http://c2.com/cgi/wiki?IterativeDevelopment[C2 wiki].

Siehe auch <<#term-iterative-development,_iterativen Entwicklung>>

// end::DE[] 