// tag::EN[]

==== Wrapper

(syn: Decorator, Adapter, Gateway) Patterns to abstract away the concrete interface or implementation of a component. Attach additional responsibilities to an object dynamically.

Depending on the sources, the semantics of the term _wrapper_ may vary.

[NOTE]
====
Comment (Gernot Starke)

The tiny differences found in literature regarding this term often don't matter in real-life. _Wrapping_ a component or building-block shall have a clear semantics within a single software system.
====
// end::EN[]

// tag::DE[]

==== Wrapper

(Syn.: Decorator, Adapter, Gateway) Muster zum Wegabstrahieren der
konkreten Schnittstelle oder Implementierung oder Komponente. Fügen
zusätzliche Verantwortlichkeiten dynamisch zu einem Objekt hinzu.

[NOTE]
====
Anmerkung (Gernot Starke)

Die winzigen Unterschiede, die sich in der Literatur zu diesem Begriff  finden, spielen im realen Leben häufig keine Rolle. Das _Wrapping_  einer Komponente oder eines Bausteins muss in einem einzelnen Softwaresystem eine klare Bedeutung haben.
====

// end::DE[]
