[#term-building-block]

// tag::EN[]
==== Building Block

General or abstract term for all kinds of artifacts from which software is constructed.
Part of the statical structure (<<term-building-block-view,Building Block View>>)
of software architecture.

Building blocks can be hierarchically structured, they may contain other (smaller) building blocks.

Some examples of alternative (concrete) names for building blocks: +
Component, module, package, namespace, class, file, program, subsystem, function, configuration, data-definition.


// end::EN[]

// tag::DE[]
==== Baustein

Allgemeiner oder abstrakter Begriff für alle Arten von Artefakten, aus
denen Software aufgebaut ist. Teil der statischen Struktur
(<<term-building-block-view,Bausteinsicht>>) von Softwarearchitektur.

Bausteine können hierarchisch strukturiert sein, sie können andere (kleinere) Bausteine enthalten.

Einige Beispiele für alternative (konkrete) Bezeichnungen von Bausteinen: +
Komponente, Modul, Paket, Namensraum, Klasse, Datei, Programm, Teilsystem, Funktion, Konfiguration, Datendefinition.

// end::DE[]

