[#term-business-context]

// tag::EN[]

==== Business Context

Shows the complete system as one <<term-blackbox,blackbox>> within its environment from a business perspective and includes a specification of all communication partners (users, IT-systems, etc.) with explanations of domain specific inputs and outputs or interfaces.
Note that the specific technical solutions for interacting with external actors should usually be omitted from the business context, as they are subject to the <<term-technical-context,technical context>>).

See <<term-context-view,Context View>>.

// end::EN[]

// tag::DE[]

==== Fachlicher Kontext

Zeigt das vollständige System als eine <<term-blackbox,Blackbox>> innerhalb seiner Umgebung aus fachlicher Perspektive und enthält eine Spezifikation aller Kommunikationspartner (Benutzer, IT-Systeme, usw.) mit Erläuterungen zu den domänenspezifischen Ein- und Ausgaben oder Schnittstellen.
Zu beachten ist, dass die spezifischen technischen Lösungen für die Interaktion mit externen Akteuren in der Regel nicht im fachlichen Kontext dargestellt werden sollten, da sie zum <<term-technical-context,technischen Kontext>>) gehören.

Siehe <<term-context-view,Kontextabgrenzung>>.

// end::DE[]
