#!/bin/bash
# WF 2022-09-19
# adapted for isaqb glossary 2022-11-02
# release a new version of the docs
mkdocs build
glossary_dir=$(pwd)
dir_name=isaqbglossary
docs_dir="$HOME/source/ghpages/$dir_name"
if [ -f "$docs_dir" ]
then
  echo "$docs_dir doesn't exist"
  echo "please create it with"
  echo "git clone https://github.com/isaqb-org/glossary --branch gh-pages --single-branch $dir_name"
  exit 1
fi
cd "$docs_dir"
echo "syncing $glossary_dir to $docs_dir ..."
rsync -avz $glossary_dir/site/*  --delete .
git add *
git commit -a -m "new release by $USER"
git push
