[#term-kerckhoffs-principle]

// tag::EN[]
==== Kerckhoffs' Principle

One of the six cryptographic axioms described 1883 in an article "La
cryptographie militaire" by the dutch cryptographer and linguist Auguste
Kerckhoffs. This axiom is still relevant today and therefore refered to as
"Kerckhoffs' Principle".

It describes that a cryptographic method must not need to be kept secret in
order to achive the security of the encrypted messages.

"The enemy knows the system" is another expression coined by the mathematician
Claude Shannon as Shannon's Maxim.

See link:https://www.schneier.com/crypto-gram/archives/2002/0515.html[Bruce Schneiers Crypto-Gram, May 15, 2002]



// end::EN[]

// tag::DE[]
==== Kerckhoffs\'sches Prinzip

Eines der sechs kryptographischen Axiome, die 1883 von dem
niederländischen Kryptographen und Linguisten Auguste Kerckhoffs in
dem Artikel „La cryptographie militaire" beschrieben wurde. Dieses
Axiom ist heute noch relevant und wird daher als „Kerckhoffs\'sches
Prinzip" bezeichnet.

Es schildert, dass eine kryptographische Methode nicht geheim gehalten
werden muss, um die verschlüsselte Botschaft zu schützen.

„Der Feind kennt das System" ist ein weiterer Ausdruck, den der
Mathematiker Claude Shannon als Shannons Maxime geprägt hat.

Siehe link:https://www.schneier.com/crypto-gram/archives/2002/0515.html[Bruce Schneiers Crypto-Gram, May 15, 2002]




// end::DE[] 