[#term-entropy]

// tag::EN[]
==== Entropy

In information theory defined as "amount of information" a message has or "unpredictability of information content".
The entropy of a crypto system is measured by the size of the keyspace.
Larger keyspaces have an increased entropy and, if not flawed by the algorithm itself, are harder to break than smaller ones.
For secure cryptographic operations it is mandatory to not only use random values as input, they should have also a high entropy.
The creation of high entropy on a computer system is non-trivial and can affect the performance of a system.

See <<schneier-96>> and Whitewood Inc. on link:https://www.blackhat.com/docs/us-15/materials/us-15-Potter-Understanding-And-Managing-Entropy-Usage-wp.pdf["Understanding and Managing Entropy"] or link:https://www.sans.org/white-papers/874/[SANS "Randomness and Entropy - An Introduction"].

// end::EN[]

// tag::DE[]
==== Entropie

In der Informationstheorie definiert als "Menge an Informationen" in
einer Nachricht oder "Unvorhersehbarkeit des Informationsgehalts". Die
Entropie eines Kryptosystems wird anhand der Größe des Schlüsselraums
gemessen. Größere Schlüsselräume haben eine höhere Entropie und sind,
wenn sie nicht durch den Algorithmus selbst fehlerhaft sind, schwerer
zu knacken als kleinere. Für sichere kryptografische Vorgänge sind
nicht nur zufällige Werte als Input vorgeschrieben, sondern sie
sollten auch eine hohe Entropie aufweisen. Die Schaffung von hoher
Entropie in einem Computersystem ist nicht trivial und kann die
Systemleistung beeinträchtigen.

Siehe <<schneier-96>> und Whitewood Inc. zu link:https://www.blackhat.com/docs/us-15/materials/us-15-Potter-Understanding-And-Managing-Entropy-Usage-wp.pdf["Understanding and Managing Entropy"]
oder link:https://www.sans.org/white-papers/874/[SANS "Randomness and Entropy - An Introduction"].

// end::DE[]
