# This is a basic workflow to help you get started with Actions

name: CI – Release Candidate

# Controls when the action will run. Triggers the workflow on push events if the pushed
# tag is a release candidate
on:
  push:
    tags:
      - "[2-9][0-9][0-9][0-9].[0-9]+-RC[0-9]+"

jobs:
  call_workflow_build_pr:
    uses: isaqb-org/github-workflows/.github/workflows/build_releasecandidate.yml@main
